### ISSUE TITLE
Readme is not displaying as expected

### ISSUE THREAD

**Issue by Guilhermeslucas** [fsouza/flask-rest-example#1]
Hi @fsouza ! This is a really simple problem, but the markdown from the README is not showing the way you expected cause there is no space between the '#' and the word after it. I can fix it!

**Comment by fsouza** [comment]
@Guilhermeslucas thanks for reporting and fixing that! This used to work in the past, but I guess it was never valid and GH wasn't complaint  :D

**Comment by Guilhermeslucas** [comment]
Thanks for the reply! Always nice to contribute! :)
